rm -rf abstract_get_drug \
abstract_get_nodrug \
assembly_geo_assembly_nodrug \
assembly_sub_assembly_drug \
assembly_sub_assembly_nodrug  \
csv \
db_path \
db_patho \
genomejp_path \
genomejp_patho \
kegg_get \
kegg_get_drug \
plot_print \
ser_abs_drug \
ser_abs_nodrug \
ser_bacts_drug \
ser_bacts_nodrug \
ser_title_drug \
ser_title_nodrug \
tmp_bact \
tmp_bact_drug \
serialization \